version: '2'
services:
  postgres:
    image: postgres:9.3
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=goapi
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  app:
    image: golang:1.12.5-alpine3.9
    volumes:
      - .:/go/src/github.com/ClementTeyssa/3PJT-API/
    working_dir: /go/src/github.com/ClementTeyssa/3PJT-API/
    command: go run main.go rooter.go
    links:
      - postgres
    ports:
      - "8180:8180"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:3pjt-api.infux.fr
      - traefik.port=8180
      - traefik.docker.network=web
    networks:
      - web
networks:
  web:
    external: true